#!/bin/bash

TARGET_PATH=$1
LANGUAGE=$2

echo "Creating target directory..."
mkdir -p $TARGET_PATH

if ! [ -d "${HOME}/.local/share/initc/${LANGUAGE}" ]; then
    echo "No language ${LANGUAGE} found."
    exit
fi

echo "Copying language preset..."
cp -r "${HOME}/.local/share/initc/${LANGUAGE}" $TARGET_PATH

echo "Finished!"

