#!/bin/bash

source "${HOME}/.local/bin/update_initc"

function initialize_project() {
TARGET_PATH=$1
LANGUAGE=$2
LANGUAGE_TEMPLATE_PATH=""

echo "Creating target directory..."
mkdir -p $TARGET_PATH


echo "Looking for ${LANGUAGE} template..."
if [ -d "${HOME}/.local/share/initc/${LANGUAGE}" ]; then
    LANGUAGE_TEMPLATE_PATH="${HOME}/.local/share/initc/${LANGUAGE}"
fi

# Custom templates override premade ones.
if [ -d "${HOME}/.local/share/initc/custom/${LANGUAGE}" ]; then
    LANGUAGE_TEMPLATE_PATH="${HOME}/.local/share/initc/custom/${LANGUAGE}"
fi

if [ "${LANGUAGE_TEMPLATE_PATH}" = "" ]; then
    echo "Didn't find language ${LANGUAGE}"
    exit
fi
echo "Template found..."

echo "Copying language template from ${LANGUAGE_TEMPLATE_PATH}..."
cp -r ${LANGUAGE_TEMPLATE_PATH}/* $TARGET_PATH

echo "Finished!"
}


COMMAND=$1

case $COMMAND in
    update)
        update_initc
        ;;
    *)
        initialize_project
        ;;
esac

